# Generated by Django 5.2.7 on 2025-10-24 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('register_number', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('backup_screenshot', models.ImageField(upload_to='screenshots/')),
                ('chat_screenshot', models.ImageField(upload_to='screenshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_device_time', models.DateTimeField()),
                ('last_backup_time_ok', models.CharField(default='No', max_length=3)),
                ('manage_google_storage_ok', models.CharField(default='No', max_length=3)),
                ('google_account_ok', models.CharField(default='No', max_length=3)),
                ('videos_toggle_ok', models.CharField(default='No', max_length=3)),
                ('chat_device_time', models.DateTimeField()),
                ('last_message_ok', models.CharField(default='No', max_length=3)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScreenshotApp.usersubmission')),
            ],
        ),
    ]
