# Generated by Django 5.2.7 on 2025-10-29 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('register_number', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('backup_screenshot', models.ImageField(upload_to='screenshots/')),
                ('chat_screenshot', models.ImageField(upload_to='screenshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_system_time', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_back_up', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_backup_today', models.CharField(blank=True, max_length=10, null=True)),
                ('manage_google_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('google_storage_account', models.CharField(blank=True, max_length=150, null=True)),
                ('google_account_org', models.CharField(blank=True, max_length=10, null=True)),
                ('include_videos_toggle', models.CharField(blank=True, max_length=10, null=True)),
                ('device_time_chat', models.CharField(blank=True, max_length=50, null=True)),
                ('last_message_ok', models.CharField(blank=True, max_length=10, null=True)),
                ('raw_text_backup', models.TextField(blank=True, null=True)),
                ('raw_text_chat', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_analysis', to='ScreenshotApp.usersubmission')),
            ],
        ),
    ]
