# Generated by Django 5.2.7 on 2025-10-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScreenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('register_number', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('chat_ss_analysis', models.TextField(blank=True, null=True)),
                ('backup_ss_analysis', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
