# Generated by Django 5.2.7 on 2025-10-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreenshotApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappanalysis',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='whatsappanalysis',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whatsappanalysis',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='whatsappanalysis',
            name='register_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
