# Generated by Django 5.2.7 on 2025-10-22 06:39

import ScreenshotApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreenshotApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScreenshotUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('register_number', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('backup_file', models.FileField(upload_to=ScreenshotApp.models.backup_upload_path)),
                ('chat_file', models.FileField(upload_to=ScreenshotApp.models.chat_upload_path)),
            ],
        ),
    ]
