# Generated by Django 5.2.7 on 2025-10-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreenshotApp', '0002_employeescreenshotupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('register_number', models.CharField(max_length=50)),
                ('backup_time', models.DateTimeField(blank=True, null=True)),
                ('last_backup_time', models.DateTimeField(blank=True, null=True)),
                ('manage_google_storage_data', models.CharField(blank=True, max_length=10, null=True)),
                ('google_account', models.CharField(blank=True, max_length=255, null=True)),
                ('videos_toggle_on', models.BooleanField(blank=True, null=True)),
                ('chats_ss_time', models.DateTimeField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeScreenshots',
        ),
    ]
