# Generated by Django 5.2.7 on 2025-10-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScreenshotApp', '0002_employeescreenshotupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('register_number', models.CharField(max_length=50)),
                ('device_time_backup', models.DateTimeField(blank=True, null=True)),
                ('last_backup_time_ok', models.CharField(max_length=3)),
                ('manage_google_storage_ok', models.CharField(max_length=3)),
                ('google_account_ok', models.CharField(max_length=3)),
                ('videos_toggle_ok', models.CharField(max_length=3)),
                ('device_time_chat', models.DateTimeField(blank=True, null=True)),
                ('last_message_ok', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeScreenshots',
        ),
    ]
